name: openstack-synchronizer
accessor:
  username: xosadmin@opencord.org
  password: "@/opt/xos/services/openstack/credentials/xosadmin@opencord.org"
dependency_graph: "/opt/xos/synchronizers/openstack/model-deps"
steps_dir: "/opt/xos/synchronizers/openstack/steps"
sys_dir: "/opt/xos/synchronizers/openstack/sys"
model_policies_dir: "/opt/xos/synchronizers/openstack/model_policies"
images_directory: "/opt/xos/images"
required_models:
  - ControllerImages
  - ControllerNetwork
  - ControllerSitePrivilege
  - ControllerSite
  - ControllerSlicePrivilege
  - ControllerSlice
  - ControllerUser
  - Image
  - Instance
  - Port
  - Role
nova:
  ca_ssl_cert: "/etc/ssl/certs/ca-certificates.crt"
  enabled: True